### ISSUE TITLE
BSD license with dependency on GPL-3.0 findhit-util

### ISSUE THREAD

**Issue by TjlHope** [cusspvz/proxywrap#36]
Hi, I found this project as we're looking to use farhadi/node-smpp (which depends on it) in a commercial project.

node-smpp is MIT and this project (from the package.json) is BSD (though I did see #3 ), but proxywrap has a dependency on findhit-util which is GPL-3.0, meaning any derivative work (i.e. project using it) needs to be GPL as well.

Would you be willing to accept a PR removing the `findhit-util` GPL dep? (AFAICT it's only used for `Util.extend` and `Util.is.object`, which could be trivially replaced with equivalent methods from lodash)

**Comment by cusspvz** [comment]
Sure, makes sense. As you said, these seem trivial and easily replaceable. If you push a PR, once we land it, I'll launch a new patch release for the license change.

**Comment by TjlHope** [comment]
Sorry about the spam there - I kept tweaking it without realising it would keep adding messages.

BTW yarn was complaining at me that the license (BSD) isn't a valid SPDX identifier - I'm assuming you mean it to be either 0BSD or BSD-3-Clause? (Not that it really matters for us)

Thanks!
